---
- name: Deploy MLOps Infrastructure
  hosts: localhost
  connection: local
  vars_files:
    - secrets.vault
  tasks:
    - name: Start infrastructure via Docker Compose
      shell: >
        docker compose -f docker-compose.yml 
        {% if not lookup('env', 'API_IMAGE') %}-f docker-compose.dev.yml {% endif %}
        up -d --wait
      environment:
        DB_USR: "{{ DB_USER }}"
        DB_PSW: "{{ DB_PASSWORD }}"
        API_IMAGE: "{{ lookup('env', 'API_IMAGE') }}"